### ISSUE TITLE
Some Applications Cannot be Pinned

### ISSUE THREAD

**Issue by Catoverflow** [dangvd/crystal-dock#13]
Some applications do show up in task manager but don't have the pin checkbox:
![image](https://github.com/dangvd/crystal-dock/assets/55503205/93f8d155-464e-4954-9231-93c0bcd43320)
google-chrome here is launched via` .desktop` file in `.local/share/applications`
To compare:
![image](https://github.com/dangvd/crystal-dock/assets/55503205/b7d7d094-745f-4a20-80ae-d0d82621542f)
There's a pin checkbox for kate and others

**Comment by dangvd** [comment]
Hi,

If the dock can't find an app on the Application Menu list, then it can't offer the option to pin/unpin it.

The reason it can't find an app on the Application Menu sometimes even when it's there, is because: on the App Menu, the command could be, for example: 'run-app-script.sh', but when it's running, the command of the task reported could be '/usr/bin/app', and so it can't match the two.

What is the command for Google Chrome in your App Menu?

Thanks,

**Comment by Catoverflow** [comment]
Yes. The exec chain is `~/.local/share/applications/google-chrome.desktop` -> `/usr/bin/google-chrome-stable` -> `/opt/google/chrome/google-chrome`

I digged a little bit more, please correct me if I'm wrong:
Program matching is interesting as the running application should be "aligned" to .desktop launchers. Before I switched to crystal dock I used latte dock and didn't notice the problem in it. Latte-dock's match function seems to be [here](https://github.com/KDE/latte-dock/blob/master/app/wm/tasktools.cpp#L146). I'm not familiar with Qt applications coding but this may be a reference?

**Comment by dangvd** [comment]
In Crystal Dock the App Menu entry is the .desktop file so yeah Crystal Dock does the matching by comparing the command of the running application with the command field of the .desktop file.

Thanks, I will look more into the link you shared.

**Comment by dangvd** [comment]
Should work better now with Crystal Dock v2.0 on Wayland. Please re-open if it's still an issue.
Thanks,

**Comment by Catoverflow** [comment]
Thanks! I tried with Firefox executed from shell script it worked.

**Comment by dangvd** [comment]
Good to hear that!
