### ISSUE TITLE
Unable to pin some applications

### ISSUE THREAD

**Issue by Detritus78** [dangvd/crystal-dock#9]
Right clicking some icons in the panel reveal no pin to panel option. i.e. Vivaldi browser, Libre office individual apps.

**Comment by Detritus78** [comment]
Operating System: MX Linux 23
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.4.11-1-liquorix-amd64 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6600 XT
Manufacturer: NZXT, Inc
Product Name: B550 UD AC

**Comment by dangvd** [comment]
I'll look more into it, but if the dock can't find an app on the Application Menu list, then it can't offer the option to pin/unpin it.

The reason it can't find an app on the Application Menu sometimes even when it's there, is because: on the App Menu, the command could be, for example: 'run-vivaldi-script.sh', but when it's running, the command of the task reported could be '/usr/bin/vivaldi', and so it can't match the two.

**Comment by Detritus78** [comment]
You may have nailed it. Is there anyway to fix it? 
![image](https://github.com/dangvd/crystal-dock/assets/104474321/bf75c3cd-db7a-44ae-835b-dfe07264edcd)

**Comment by Detritus78** [comment]
> I'll look more into it, but if the dock can't find an app on the Application Menu list, then it can't offer the option to pin/unpin it.
> 
> The reason it can't find an app on the Application Menu sometimes even when it's there, is because: on the App Menu, the command could be, for example: 'run-vivaldi-script.sh', but when it's running, the command of the task reported could be '/usr/bin/vivaldi', and so it can't match the two.

This fixed it! It is pinned now. 
![image](https://github.com/dangvd/crystal-dock/assets/104474321/a4b5cb54-7cdd-4863-a308-1d18b4a3e3de)
